### ISSUE TITLE
[3주차] 5장 웹어댑터 구현하기 - 김세윤

### ISSUE THREAD

**Issue by ksy90101** [Meet-Coder-Study/Get-Your-Hands-Dirty-on-Clean-Architecture#36]
## 컨트롤러 나누기

> 클래스마다 코드는 적을 수록 좋다. 코드가 적으면 파악하는 것에 난이도가 낮아진다. 

모든 연산을 단일 컨트롤러에 넣는 것이 데이터 구조의 재활용을 촉진한다는 데 있다. 그러나 이게 좋을까? 헷갈림만 가지게 될것이다. 따라서, 각 연산에 대해 가급적이면 별도의 패키지 안에 별도의 컨트롤러를 만들며 가급적 메서드와 클래스명은 유스케이스를 최대한 반영해서 지어야 한다. 서로 다른 연산에 대한 동시 작업이 쉬워진다는 것이 가장 큰 장점이다.

책에서는 위와같이, 컨트롤러를 나누는 작업을 이야기 합니다. 저는 서비스도 그렇고 컨트롤러도 그렇고, 간단한 CRUD는 한곳에 모아두고, 그 외적인 유즈케이스가 생길때, 분리하는게 좋다고 생각이 드는데요. 또한 유즈케이스가 연관이 있다면 (예를들면, 회원가입, 로그인) 묶는게 더 좋다고 생각이 들어요.

여러분들은 이 부분으 봤을때 어떻게 느꼈는지 궁금합니다 :)

**Comment by ksy90101** [comment]
이건 트레이드 오프일거 같은데, 모놀리틱에서는 객체가 엄청 많아지니, 이걸 조심하게 사용해야 하지 않을까 합니다.
도메인별로 1차적으로 분리하고, 상황에 따라 다르게 해야 하지 않을까 합니다.

**Comment by Wave1994-Hoon** [comment]
도메인 별로 쪼개진 MSA 라면 각 유스케이스마다 쪼개는 것이 유지보수에 더 좋은 것 같습니다.
하지만 모놀리스에서는 너무 많은 클래스가 생성이 되기 때문에 파국일 것 같습니다 ...
