### ISSUE TITLE
[3주차] 5장. 웹 어댑터 구현하기

### ISSUE THREAD

**Issue by pkch93** [Meet-Coder-Study/Get-Your-Hands-Dirty-on-Clean-Architecture#38]
5장에서 저자는 컨트롤러에 대해서도 UseCase의 이름에 맞춰서 컨트롤러를 만드는 것을 선호하고 있는데요.

이렇게 되면 사실상 컨트롤러 - UseCase가 1:1인 상태가 될 것으로 보이는데요. 클래스를 잘게 쪼갠다는 점에서 좋아보이긴 하지만 그만큼 관리해야할 클래스가 너무 많아지는 것으로도 보여서요.

도메인 별로 컨트롤러를 구성하면 어떨까 싶기도 한데 어떻게 생각하시나요?

**Comment by pkch93** [comment]
결국 상황에 따라 다르다. 상황에 맞춰서 적절한 크기로 컨트롤러를 구성하는 게 적절해보임

**Comment by Wave1994-Hoon** [comment]
세윤님 질문과 비슷한 것 같아서 복붙해왔습니다. !! 

제 개인적인 생각으로 도메인 별로 나뉜 MSA 라면 각 유스케이스마다 쪼갠다면 클래스 이름만 보고 어떤 기능들을 하는지 명확히 알 수 있어서 유지보수에 더 좋을 것 같다고 생각합니다. 하지만 모놀리스에서는 너무 많은 클래스가 생성이 되기 때문에 파국일 것 같습니다 ...
