### ISSUE TITLE
[3주차] 5장. 웹 어댑터 구현하기 - 공은미

### ISSUE THREAD

**Issue by eunmik** [Meet-Coder-Study/Get-Your-Hands-Dirty-on-Clean-Architecture#40]
p.61 - 컨트롤러명과 서비스명에 대해서도 잘 생각해봐야 한다. 예를 들어, CreateAccount보다는 RegisterAccount가 더 나은 이름 같지 않은가? 
BuckPal 예제에서 계좌를 생성하는 유일한 방법은 사용자가 계좌를 등록하는 방법 뿐이다. 

RegisterAccount나 CreateAccount나 비슷한 거 같은데.. RegisterAccount가 더 나은 이름인 것 같다는 것에 여러분들은 동의하시나요??

**Comment by Wave1994-Hoon** [comment]
저는 사내에서 개발할 때 generateWith( ), extractFrom( )  등 동사를 풍부하게 사용하려고 노력하고 있습니다.

프로그래밍 언어라는 것이 결국 인간이 읽는 언어이고, 이것을 단순히 CRUD 4가지의 동사로만 표현하기에는 부족하다고 생각이듭니다. ㅎㅎㅎ
(물론 네이밍이 복잡해질 수 있다곤 생각이 듭니다. 이건 같은 프로젝트를 개발하는 인원과 어느정도 협의가 필요해보여요)

**Comment by eunmik** [comment]
> 저는 사내에서 개발할 때 generateWith( ), extractFrom( ) 등 동사를 풍부하게 사용하려고 노력하고 있습니다.
> 
> 프로그래밍 언어라는 것이 결국 인간이 읽는 언어이고, 이것을 단순히 CRUD 4가지의 동사로만 표현하기에는 부족하다고 생각이듭니다. ㅎㅎㅎ (물론 네이밍이 복잡해질 수 있다곤 생각이 듭니다. 이건 같은 프로젝트를 개발하는 인원과 어느정도 협의가 필요해보여요)

감사합니다!!! 4가지의 동사만으로 표현하기엔 턱없이 부족하죠...

**Comment by eunmik** [comment]
유스케이스 입장에서 은행 계좌 생성 해주세요 보다는 계좌 등록해주세요 라는 의미가 더 와닿기 때문에 ...
포괄적인 단어보다는 의미가 더 와닿는 동사를 사용한다
