### ISSUE TITLE
[3주차] 5장. 웹 어댑터 구현하기 - 구민규

### ISSUE THREAD

**Issue by kooku0** [Meet-Coder-Study/Get-Your-Hands-Dirty-on-Clean-Architecture#41]
> 보통 테스트 코드는 더 추상적이라서 프로덕션 코드에 비해 파악하기가 어려울 때가 많다. 따라서 특정 프로덕션 코드에 해당하는 테스트 코드를 찾기 어렵다.

라는 글이 있었는데 테스트 코드가 프로덕션 코드에 비해 추상적이다 라는 말은 구현이 없어서 그렇게 말한거겠죠? 테스트 코드는 파악하기 힘들거나 읽기 힘들면 안된다고 생각해서요. 그리고 당연히 프로뎍션 코드보다 파악하기도 쉬워야 한다고 생각해서..

**Comment by Wave1994-Hoon** [comment]
저자의 의도는 테스트 코드는 단순히 구현 된 메서드를 호출하기 때문에 추상적이라고 표현하지 않았나 싶습니다. 

책 읽으면서 저 부분은 넘겼었는데, 좀 더 자세히 읽어봐야겠네요 ㅠㅠ
